### ISSUE TITLE
Validate Fields in YAML

### ISSUE THREAD

**Issue by tri-adam** [sylabs/fuzzctl#2]
The CLI doesn't currently detect unknown fields in the workflow YAML. For example, this is accepted even though `foo` isn't a valid key:

```
version: 0.1
foo: bar
workflow:
  name: wf
  jobs:
    jobA:
      image: library://alpine:latest
      command: ["date"]
```

We should validate keys somehow (and maybe we could provide a `validate` command in the CLI?)
